INSERT INTO users (name, age) VALUES ("LALA",1);
INSERT INTO users (name, age) VALUES ("dfd",2);
INSERT INTO users (name, age) VALUES ("dsgdsg",33);
INSERT INTO users (name, age) VALUES ("hjhgjg",33);
INSERT INTO users (name, age) VALUES ("tyyy",5);
INSERT INTO users (name, age) VALUES ("bfdvgdfv",155);
INSERT INTO users (name, age) VALUES ("yfhjfh",44);
INSERT INTO users (name, age) VALUES ("d",90);
INSERT INTO users (name, age) VALUES ("fgfdg",50);
INSERT INTO users (name, age) VALUES ("yjujuy",20);
INSERT INTO users (name, age) VALUES ("gdfg",45);
INSERT INTO users (name, age) VALUES ("vdfv",99);
INSERT INTO users (name, age) VALUES ("jhhj",44);
INSERT INTO users (name, age) VALUES ("dddd",22);
INSERT INTO users (name, age) VALUES ("fffff",6);
INSERT INTO users (name, age) VALUES ("gggg",42);
INSERT INTO users (name, age) VALUES ("hhhhh",88);
INSERT INTO users (name, age) VALUES ("jjjjj",50);
INSERT INTO users (name, age) VALUES ("www",33);
INSERT INTO users (name, age) VALUES ("lll",17);


INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("urghl", "product", 61551, NULL, NULL);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("jknkjn", "product", 2332, NULL, NULL);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("urghl", "charity", 452, NULL, NULL);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("urghl", "charity", 354343, NULL, NULL);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("urghl", "bike", 34534, NULL, NULL);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("urghl", "bike", 5235, NULL, NULL);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("urghl", "desk", 36, NULL, NULL);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("urghl", "desk", 85865, NULL, NULL);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("urghl", "organizer", 35, NULL, NULL);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("urghl", "pool", 8686, NULL, NULL);

INSERT INTO pledges (amount, user_id, project_id) VALUES (1, "a", "1");
INSERT INTO pledges (amount, user_id, project_id) VALUES (2, "b", "2");
INSERT INTO pledges (amount, user_id, project_id) VALUES (3, "c", "3");
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, "a", "1");
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, "a", "1");
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, "a", "1");
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, "a", "1");
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, "a", "1");
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, "a", "1");
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, "a", "1");
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, "a", "1");
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, "a", "1");
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, "a", "1");
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, "a", "1");
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, "a", "1");
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, "a", "1");
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, "a", "1");
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, "a", "1");
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, "a", "1");
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, "a", "1");
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, "a", "1");
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, "a", "1");
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, "a", "1");
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, "a", "1");
INSERT INTO pledges (amount, user_id, project_id) VALUES (354, "a", "1");
INSERT INTO pledges (amount, user_id, project_id) VALUES (154354, "a", "1");
INSERT INTO pledges (amount, user_id, project_id) VALUES (1354, "axxx", "1");
INSERT INTO pledges (amount, user_id, project_id) VALUES (1345345, "a", "1");
INSERT INTO pledges (amount, user_id, project_id) VALUES (153, "ccc", "1");
INSERT INTO pledges (amount, user_id, project_id) VALUES (12532543, "yyy", "1");
